### ISSUE TITLE
Failed to compile [...] Maximum sampler register index exceeded

### ISSUE THREAD

**Issue by ThreeDeeJay** [JakobPCoder/ReshadeMotionEstimation#3]
```
 [72200] | ERROR | Failed to compile "C:\Games\Steam\steamapps\common\Grand Theft Auto San Andreas\reshade-shaders\Shaders\MotionEstimation.fx":
C:\Games\Steam\steamapps\common\Grand Theft Auto San Andreas\Shader@0x1E0A9A80(776,11-25): error X4509: maximum sampler register index exceeded, target has 16 slots, manual bind to slot s18 failed
```
![gta-sa_wONa9CUJYg](https://user-images.githubusercontent.com/71472458/209792056-9f2b6edc-e6de-4193-ada2-fc31c39fbdfb.png)

Using ReShade 5.5.2 Addon on Win 11

**Comment by ThreeDeeJay** [comment]
Just tested it with ReShade 5.9.2 and it finally loads.

![citra-qt_Pa9lF9ilSh](https://github.com/JakobPCoder/ReshadeMotionEstimation/assets/71472458/1c307f93-a0bc-4216-bb16-df6153e53047)

Though I'm not sure how to use this. I may have misunderstood the purpose of this shader so I have some questions:
Does it do motion interpolation to increase games' FPS, or just vector estimation? what are the practical uses?
Does it need the [Optical Flow SDK](https://developer.nvidia.com/opticalflow/download) or some other dependency? If so, how do we install it?

**Comment by catv1** [comment]
i am using reshade 6.1.1 and have this problem
